import { Challenge } from '../types';

export const INITIAL_CHALLENGES: Challenge[] = [
  // CINE Y SERIES (Arte)
  { emoji: "🤫🐑", phrase: "El silencio de los corderos", category: "Arte", subcategory: "Película" },
  { emoji: "🚢🧊", phrase: "Titanic", category: "Arte", subcategory: "Película" },
  { emoji: "🦁👑", phrase: "El Rey León", category: "Arte", subcategory: "Película" },
  { emoji: "🃏", phrase: "Joker", category: "Arte", subcategory: "Película" },
  { emoji: "🎈🏠", phrase: "Up", category: "Arte", subcategory: "Película" },
  { emoji: "💀🎸", phrase: "Coco", category: "Arte", subcategory: "Película" },
  { emoji: "⚡👓", phrase: "Harry Potter", category: "Arte", subcategory: "Película" },
  { emoji: "⚔️🌌", phrase: "Star Wars", category: "Arte", subcategory: "Película" },
  { emoji: "🦈🌊", phrase: "Tiburón", category: "Arte", subcategory: "Película" },
  { emoji: "🦖🌴", phrase: "Jurassic Park", category: "Arte", subcategory: "Película" },
  { emoji: "🦇🏙️", phrase: "Batman", category: "Arte", subcategory: "Película" },
  { emoji: "🥊🇺🇸", phrase: "Rocky", category: "Arte", subcategory: "Película" },
  { emoji: "💊🕶️", phrase: "The Matrix", category: "Arte", subcategory: "Película" },
  { emoji: "💍🌋", phrase: "El Señor de los Anillos", category: "Arte", subcategory: "Película" },
  { emoji: "🍫🏭", phrase: "Charlie y la fábrica de chocolate", category: "Arte", subcategory: "Película" },
  { emoji: "🧟‍♂️🏹", phrase: "The Walking Dead", category: "Arte", subcategory: "Serie" },
  { emoji: "🏰👸🐉", phrase: "Juego de Tronos", category: "Arte", subcategory: "Serie" },
  { emoji: "🤠🧸", phrase: "Toy Story", category: "Arte", subcategory: "Película" },
  { emoji: "👽👉", phrase: "E.T.", category: "Arte", subcategory: "Película" },
  { emoji: "👟🏃‍♂️", phrase: "Forrest Gump", category: "Arte", subcategory: "Película" },
  { emoji: "🐰🕳️☕", phrase: "Alicia en el país de las maravillas", category: "Arte", subcategory: "Película" },
  { emoji: "🚿🔪😱", phrase: "Psicosis", category: "Arte", subcategory: "Película" },
  { emoji: "🪐🚀👨‍🚀", phrase: "Interstellar", category: "Arte", subcategory: "Película" },
  { emoji: "🩰🦢🖤", phrase: "Cisne Negro", category: "Arte", subcategory: "Película" },
  { emoji: "🐭👨‍🍳🥘", phrase: "Ratatouille", category: "Arte", subcategory: "Película" },
  { emoji: "🤡🎈🩸", phrase: "It", category: "Arte", subcategory: "Película" },
  { emoji: "🏎️⛽🏁", phrase: "Fast & Furious", category: "Arte", subcategory: "Película" },

  // GEOGRAFÍA
  { emoji: "🗼🇫🇷", phrase: "Francia", category: "Geografía", subcategory: "País" },
  { emoji: "🏟️🇮🇹", phrase: "Italia", category: "Geografía", subcategory: "País" },
  { emoji: "⛩️🇯🇵", phrase: "Japón", category: "Geografía", subcategory: "País" },
  { emoji: "🗽🍎", phrase: "Nueva York", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "💂‍♂️🇬🇧", phrase: "Londres", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🧱🐉🇨🇳", phrase: "La Gran Muralla China", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏔️🇳🇵", phrase: "Everest", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🐫🇪🇬", phrase: "Egipto", category: "Geografía", subcategory: "País" },
  { emoji: "🇧🇷⚽🏟️", phrase: "Brasil", category: "Geografía", subcategory: "País" },
  { emoji: "🦘🇦🇺", phrase: "Australia", category: "Geografía", subcategory: "País" },
  { emoji: "🥨🍺🇩🇪", phrase: "Alemania", category: "Geografía", subcategory: "País" },
  { emoji: "🧀🏔️🇨🇭", phrase: "Suiza", category: "Geografía", subcategory: "País" },
  { emoji: "🍁🇨🇦", phrase: "Canadá", category: "Geografía", subcategory: "País" },
  { emoji: "🐂🇪🇸", phrase: "España", category: "Geografía", subcategory: "País" },
  { emoji: "🌷🚲🇳🇱", phrase: "Países Bajos", category: "Geografía", subcategory: "País" },
  { emoji: "🎭🛶🇮🇹", phrase: "Venecia", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🌉🇺🇸", phrase: "San Francisco", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🌵🎺🇲🇽", phrase: "México", category: "Geografía", subcategory: "País" },
  { emoji: "🥐🗼🇫🇷", phrase: "París", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🍣🍱🇯🇵", phrase: "Tokio", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🍕🏛️🇮🇹", phrase: "Roma", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "⛪⚽🇪🇸", phrase: "Barcelona", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🏔️🦁🇹🇿", phrase: "Kilimanjaro", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🌳🦜🌊", phrase: "Amazonas", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏜️☀️🐫", phrase: "Sahara", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🌊🇨🇦💦", phrase: "Cataratas del Niágara", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🌊🇦🇷💦", phrase: "Cataratas Iguazú", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏜️🦅🦅", phrase: "Gran Cañón", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🐧🧊🇦🇶", phrase: "Antártida", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏔️🐑🇦🇷", phrase: "Patagonia", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🐻🌲🇺🇸", phrase: "Yellowstone", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🧱⛰️🇵🇪", phrase: "Machu Picchu", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🗼🥐🏛️", phrase: "Torre Eiffel", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏟️⚔️🇮🇹", phrase: "Coliseo Romano", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🗽⭐🇺🇸", phrase: "Estatua de la Libertad", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🕰️🇬🇧🔔", phrase: "Big Ben", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🐚🎭🇦🇺", phrase: "Ópera de Sídney", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏙️🇦🇪🏢", phrase: "Burj Khalifa", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏢🇮🇹🍕", phrase: "Torre de Pisa", category: "Geografía", subcategory: "Lugar" },
  { emoji: "⛪🏗️🇪🇸", phrase: "Sagrada Familia", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🗿🏝️🇨🇱", phrase: "Isla de Pascua", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🪸🐠🇦🇺", phrase: "Gran Barrera de Coral", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏔️🧘‍♂️🕉️", phrase: "Himalaya", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏔️🇦🇷⛰️", phrase: "Andes", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏔️⛷️❄️", phrase: "Alpes", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🐊🛶🇪🇬", phrase: "Río Nilo", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🏛️🌊🇬🇷", phrase: "Santorini", category: "Geografía", subcategory: "Lugar" },
  { emoji: "🎰🎲🇺🇸", phrase: "Las Vegas", category: "Geografía", subcategory: "Ciudad" },
  { emoji: "🏙️🏮🇭🇰", phrase: "Hong Kong", category: "Geografía", subcategory: "Ciudad" },

  // REFRANES
  { emoji: "💧🚫🏃‍♂️", phrase: "Agua que no has de beber déjala correr", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🐦✊🌳", phrase: "Más vale pájaro en mano que ciento volando", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🐴👀🤐", phrase: "A caballo regalado no le mires el diente", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🐶🗣️🦷", phrase: "Perro ladrador poco mordedor", category: "Refranes", subcategory: "Refrán" },
  { emoji: "👄🪰🤐", phrase: "En boca cerrada no entran moscas", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🐢💨🐇", phrase: "Vísteme despacio que tengo prisa", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🍞🍷", phrase: "Al pan, pan y al vino, vino", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🍎🌳📍", phrase: "La manzana no cae lejos del árbol", category: "Refranes", subcategory: "Refrán" },
  { emoji: "🌙🏙️🌄", phrase: "A quien madruga Dios le ayuda", category: "Refranes", subcategory: "Refrán" },
  { emoji: "👞🛠️", phrase: "Zapatero a tus zapatos", category: "Refranes", subcategory: "Refrán" },

  // DEPORTE
  { emoji: "🇧🇷⚽👑", phrase: "Pelé", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇦🇷🖐️⚽", phrase: "Diego Maradona", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🐐⚽🇦🇷", phrase: "Lionel Messi", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇵🇹⚽7️⃣", phrase: "Cristiano Ronaldo", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇪🇸🎾💪", phrase: "Rafael Nadal", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🏀🐐👟", phrase: "Michael Jordan", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🏀🐍", phrase: "Kobe Bryant", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🏀🎯", phrase: "Stephen Curry", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🥊🐝", phrase: "Muhammad Ali", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🥊💰", phrase: "Floyd Mayweather", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇧🇷🏎️🌧️", phrase: "Ayrton Senna", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇩🇪🏎️🔴", phrase: "Michael Schumacher", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇬🇧🏎️", phrase: "Lewis Hamilton", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🇳🇱🏎️🦁", phrase: "Max Verstappen", category: "Deporte", subcategory: "Atleta" },
  { emoji: "🏟️👑", phrase: "Santiago Bernabéu", category: "Deporte", subcategory: "Estadio" },
  { emoji: "🏟️🔵🔴", phrase: "Camp Nou", category: "Deporte", subcategory: "Estadio" },
  { emoji: "🎾🍓", phrase: "Wimbledon", category: "Deporte", subcategory: "Torneo" },
  { emoji: "🏃‍♂️🚩", phrase: "Fuera de juego", category: "Deporte", subcategory: "Concepto" },
  { emoji: " baseball 💥", phrase: "Home Run", category: "Deporte", subcategory: "Concepto" },
  { emoji: "🏎️🔧⏱️", phrase: "Pit Stop", category: "Deporte", subcategory: "Concepto" },
  { emoji: "⚽⚽⚽🎩", phrase: "Hat-Trick", category: "Deporte", subcategory: "Concepto" },
  { emoji: "🥊😵", phrase: "Knockout", category: "Deporte", subcategory: "Concepto" },
  { emoji: "🎾🏆🏆🏆🏆", phrase: "Grand Slam", category: "Deporte", subcategory: "Torneo" },

  // GASTRONOMÍA
  { emoji: "🧱🥩🍅", phrase: "Lasaña", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🐟🍋🥗", phrase: "Ceviche", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥓🥚🍝", phrase: "Pasta carbonara", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🐔🍞🍔", phrase: "Burger de pollo", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍍🥩🌮", phrase: "Tacos al pastor", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🧀🎂🍓", phrase: "Tarta de queso", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥢🥓🍜", phrase: "Chow-mein", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥬🔥🌶️", phrase: "Kimchi", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍚🥣🐄", phrase: "Risotto", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🇭🇺🥩🥘", phrase: "Goulash", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥚🥔🍳", phrase: "Tortilla española", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍅🥣🥖", phrase: "Gazpacho", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍆🥩🧀", phrase: "Moussaka", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🐟🥢🍣", phrase: "Sashimi", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🧆🌿🌯", phrase: "Falafel", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥣🍯🏜️", phrase: "Hummus", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🐭🥘🍲", phrase: "Ratatouille", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥟🥢🇨🇳", phrase: "Dumplings chinos", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🌯🔥🌮", phrase: "Fajitas", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🌯🌶️🔥", phrase: "Enchiladas", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍃🌽🌮", phrase: "Tamales", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🧀🔥🧀", phrase: "Halloumi frito", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍟🧀🇨🇦", phrase: "Poutine", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🧧🍝🇮🇹", phrase: "Tortellini", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥣🩸🇷🇺", phrase: "Borscht", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥟🇵🇱🥔", phrase: "Pierogi", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥣🍳🇰🇷", phrase: "Bibimbap", category: "Gastronomía", subcategory: "Plato" },

  // PALABRA ALEATORIA
  { emoji: "⏪🥺", phrase: "Nostalgia", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🤫🔒", phrase: "Secreto", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🕵️‍♂️🔍", phrase: "Misterio", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🛤️🔮", phrase: "Destino", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🏜️💧❓", phrase: "Espejismo", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "☀️🌑", phrase: "Eclipse", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🍎⬇️🌍", phrase: "Gravedad", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🗣️👂💬", phrase: "Rumor", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🌇🦇🌒", phrase: "Crepúsculo", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🔇🤫💨", phrase: "Silencio", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🔄🤯♾️", phrase: "Paradoja", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "☁️👼✨", phrase: "Paraíso", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "💓🩺💉", phrase: "Latido", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🌧️🏠🛡️", phrase: "Refugio", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🏜️🐪🔥", phrase: "Desierto", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "👁️👁️✨", phrase: "Mirada", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🎁😲🎈", phrase: "Sorpresa", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "😈👦🤪", phrase: "Travesura", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🎩✨🐇", phrase: "Ilusión", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🪞👤💨", phrase: "Espejo", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "🙈🌳🏃", phrase: "Escondite", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "⚔️🛡️🔥", phrase: "Desafío", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "👁️⬇️⬆️", phrase: "Parpadeo", category: "Palabra Aleatoria", subcategory: "Concepto" },
  { emoji: "📸✨💥", phrase: "Destello", category: "Palabra Aleatoria", subcategory: "Concepto" }
];
