import { Challenge } from '../types';

export const INITIAL_CHALLENGES: Challenge[] = [
  // CINE Y SERIES (Minimalismo puro)
  { emoji: "🤫🐑", phrase: "El silencio de los corderos", category: "Arte" },
  { emoji: "🚢🧊", phrase: "Titanic", category: "Arte" },
  { emoji: "🦁👑", phrase: "El Rey León", category: "Arte" },
  { emoji: "🃏", phrase: "Joker", category: "Arte" },
  { emoji: "🎈🏠", phrase: "Up", category: "Arte" },
  { emoji: "💀🎸", phrase: "Coco", category: "Arte" },
  { emoji: "⚡", phrase: "Harry Potter", category: "Arte" },
  { emoji: "⚔️🌌", phrase: "Star Wars", category: "Arte" },
  { emoji: "🦈", phrase: "Tiburón", category: "Arte" },
  { emoji: "🦖", phrase: "Jurassic Park", category: "Arte" },
  { emoji: "🦇", phrase: "Batman", category: "Arte" },
  { emoji: "🥊", phrase: "Rocky", category: "Arte" },
  { emoji: "💊", phrase: "The Matrix", category: "Arte" },
  { emoji: "💍", phrase: "El Señor de los Anillos", category: "Arte" },
  { emoji: "🍫🏭", phrase: "Charlie y la fábrica de chocolate", category: "Arte" },
  { emoji: "🧟‍♂️", phrase: "The Walking Dead", category: "Arte" },
  { emoji: "🏰👸🐉", phrase: "Juego de Tronos", category: "Arte" },
  { emoji: "🤠🧸", phrase: "Toy Story", category: "Arte" },
  { emoji: "👽👉", phrase: "E.T.", category: "Arte" },
  { emoji: "👟🏃‍♂️", phrase: "Forrest Gump", category: "Arte" },
  { emoji: "🐰🕳️", phrase: "Alicia en el país de las maravillas", category: "Arte" },
  { emoji: "🚿🔪", phrase: "Psicosis", category: "Arte" },
  { emoji: "🪐", phrase: "Interstellar", category: "Arte" },
  { emoji: "🩰🦢", phrase: "Cisne Negro", category: "Arte" },
  { emoji: "🐭👨‍🍳", phrase: "Ratatouille", category: "Arte" },
  { emoji: "🤡🎈", phrase: "It", category: "Arte" },
  { emoji: "🏎️⛽", phrase: "Fast & Furious", category: "Arte" },

  // GEOGRAFÍA (Iconos únicos)
  { emoji: "🗼", phrase: "Francia", category: "Geografía" },
  { emoji: "🏟️", phrase: "Italia", category: "Geografía" },
  { emoji: "⛩️", phrase: "Japón", category: "Geografía" },
  { emoji: "🗽", phrase: "Nueva York", category: "Geografía" },
  { emoji: "💂‍♂️", phrase: "Londres", category: "Geografía" },
  { emoji: "🧱🐉", phrase: "La Gran Muralla China", category: "Geografía" },
  { emoji: "🏔️", phrase: "Everest", category: "Geografía" },
  { emoji: "🐫", phrase: "Egipto", category: "Geografía" },
  { emoji: "🏖️💃", phrase: "Brasil", category: "Geografía" },
  { emoji: "🦘", phrase: "Australia", category: "Geografía" },
  { emoji: "🥨🍺", phrase: "Alemania", category: "Geografía" },
  { emoji: "🧀🏔️", phrase: "Suiza", category: "Geografía" },
  { emoji: "🍁", phrase: "Canadá", category: "Geografía" },
  { emoji: "🐂", phrase: "España", category: "Geografía" },
  { emoji: "🌷🚲", phrase: "Países Bajos", category: "Geografía" },
  { emoji: "🎭🛶", phrase: "Venecia", category: "Geografía" },
  { emoji: "🌉", phrase: "San Francisco", category: "Geografía" },
  { emoji: "🌵🎺", phrase: "México", category: "Geografía" },

  // REFRANES (Aquí sí hace falta un poco más de contexto)
  { emoji: "💧🚫🏃‍♂️", phrase: "Agua que no has de beber déjala correr", category: "Refranes" },
  { emoji: "🐦✊🌳", phrase: "Más vale pájaro en mano que ciento volando", category: "Refranes" },
  { emoji: "🐴👀🤐", phrase: "A caballo regalado no le mires el diente", category: "Refranes" },
  { emoji: "🐶🗣️🦷", phrase: "Perro ladrador poco mordedor", category: "Refranes" },
  { emoji: "👄🪰🤐", phrase: "En boca cerrada no entran moscas", category: "Refranes" },
  { emoji: "🐢💨🐇", phrase: "Vísteme despacio que tengo prisa", category: "Refranes" },
  { emoji: "🍞🍷", phrase: "Al pan, pan y al vino, vino", category: "Refranes" },
  { emoji: "🍎🌳📍", phrase: "La manzana no cae lejos del árbol", category: "Refranes" },
  { emoji: "🌙🏙️🌄", phrase: "A quien madruga Dios le ayuda", category: "Refranes" },
  { emoji: "👞🛠️", phrase: "Zapatero a tus zapatos", category: "Refranes" },

  // DEPORTE
  { emoji: "🇧🇷⚽👑", phrase: "Pelé", category: "Deporte" },
  { emoji: "🇦🇷🖐️⚽", phrase: "Diego Maradona", category: "Deporte" },
  { emoji: "🐐⚽🇦🇷", phrase: "Lionel Messi", category: "Deporte" },
  { emoji: "🇵🇹⚽7️⃣", phrase: "Cristiano Ronaldo", category: "Deporte" },
  { emoji: "🇪🇸🎾💪", phrase: "Rafael Nadal", category: "Deporte" },
  { emoji: "🏀🐐👟", phrase: "Michael Jordan", category: "Deporte" },
  { emoji: "🏀🐍", phrase: "Kobe Bryant", category: "Deporte" },
  { emoji: "🏀🎯", phrase: "Stephen Curry", category: "Deporte" },
  { emoji: "🥊🐝", phrase: "Muhammad Ali", category: "Deporte" },
  { emoji: "🥊💰", phrase: "Floyd Mayweather", category: "Deporte" },
  { emoji: "🇧🇷🏎️🌧️", phrase: "Ayrton Senna", category: "Deporte" },
  { emoji: "🇩🇪🏎️🔴", phrase: "Michael Schumacher", category: "Deporte" },
  { emoji: "🇬🇧🏎️", phrase: "Lewis Hamilton", category: "Deporte" },
  { emoji: "🇳🇱🏎️🦁", phrase: "Max Verstappen", category: "Deporte" },
  { emoji: "🏟️👑", phrase: "Santiago Bernabéu", category: "Deporte" },
  { emoji: "🏟️🔵🔴", phrase: "Camp Nou", category: "Deporte" },
  { emoji: "🎾🍓", phrase: "Wimbledon", category: "Deporte" },
  { emoji: "🏃‍♂️🚩", phrase: "Fuera de juego", category: "Deporte" },
  { emoji: "⚾💥", phrase: "Home Run", category: "Deporte" },
  { emoji: "🏎️🔧⏱️", phrase: "Pit Stop", category: "Deporte" },
  { emoji: "⚽⚽⚽🎩", phrase: "Hat-Trick", category: "Deporte" },
  { emoji: "🥊😵", phrase: "Knockout", category: "Deporte" },
  { emoji: "🎾🏆🏆🏆🏆", phrase: "Grand Slam", category: "Deporte" },

  // GASTRONOMÍA (Nueva lista ampliada)
  { emoji: "🧱🥩", phrase: "Lasaña", category: "Gastronomía" },
  { emoji: "🐟🍋", phrase: "Ceviche", category: "Gastronomía" },
  { emoji: "🥓🥚", phrase: "Pasta carbonara", category: "Gastronomía" },
  { emoji: "🐔🍞", phrase: "Burger de pollo", category: "Gastronomía" },
  { emoji: "🍍🥩", phrase: "Tacos al pastor", category: "Gastronomía" },
  { emoji: "🧀🎂", phrase: "Tarta de queso", category: "Gastronomía" },
  { emoji: "🥢🥓", phrase: "Chow-mein", category: "Gastronomía" },
  { emoji: "🥬🔥", phrase: "Kimchi", category: "Gastronomía" },
  { emoji: "🍚🥣", phrase: "Risotto", category: "Gastronomía" },
  { emoji: "🇭🇺🥩", phrase: "Goulash", category: "Gastronomía" },
  { emoji: "🥚🥔", phrase: "Tortilla española", category: "Gastronomía" },
  { emoji: "🍅🥣", phrase: "Gazpacho", category: "Gastronomía" },
  { emoji: "🍆🥩", phrase: "Moussaka", category: "Gastronomía" },
  { emoji: "🐟🥢", phrase: "Sashimi", category: "Gastronomía" },
  { emoji: "🧆🌿", phrase: "Falafel", category: "Gastronomía" },
  { emoji: "🥣🍯", phrase: "Hummus", category: "Gastronomía" },
  { emoji: "🐭🥘", phrase: "Ratatouille", category: "Gastronomía" },
  { emoji: "🥟🥢", phrase: "Dumplings chinos", category: "Gastronomía" },
  { emoji: "🌯🔥", phrase: "Fajitas", category: "Gastronomía" },
  { emoji: "🌯🌶️", phrase: "Enchiladas", category: "Gastronomía" },
  { emoji: "🍃🌽", phrase: "Tamales", category: "Gastronomía" },
  { emoji: "🧀🔥", phrase: "Halloumi frito", category: "Gastronomía" },
  { emoji: "🍟🧀", phrase: "Poutine", category: "Gastronomía" },
  { emoji: "🧧🍝", phrase: "Tortellini", category: "Gastronomía" },
  { emoji: "🥣🩸", phrase: "Borscht", category: "Gastronomía" },
  { emoji: "🥟🇵🇱", phrase: "Pierogi", category: "Gastronomía" },
  { emoji: "🥣🍳", phrase: "Bibimbap", category: "Gastronomía" },

  // PALABRA ALEATORIA (Conceptos abstractos y de ingenio)
  { emoji: "⏪🥺", phrase: "Nostalgia", category: "Palabra Aleatoria" },
  { emoji: "🤫🔒", phrase: "Secreto", category: "Palabra Aleatoria" },
  { emoji: "🕵️‍♂️🔍", phrase: "Misterio", category: "Palabra Aleatoria" },
  { emoji: "🛤️🔮", phrase: "Destino", category: "Palabra Aleatoria" },
  { emoji: "🏜️💧❓", phrase: "Espejismo", category: "Palabra Aleatoria" },
  { emoji: "☀️🌑", phrase: "Eclipse", category: "Palabra Aleatoria" },
  { emoji: "🍎⬇️", phrase: "Gravedad", category: "Palabra Aleatoria" },
  { emoji: "🗣️👂", phrase: "Rumor", category: "Palabra Aleatoria" },
  { emoji: "🌇🦇", phrase: "Crepúsculo", category: "Palabra Aleatoria" },
  { emoji: "🔇🤫", phrase: "Silencio", category: "Palabra Aleatoria" },
  { emoji: "🔄🤯", phrase: "Paradoja", category: "Palabra Aleatoria" },
  { emoji: "☁️👼", phrase: "Paraíso", category: "Palabra Aleatoria" },
  { emoji: "💓🩺", phrase: "Latido", category: "Palabra Aleatoria" },
  { emoji: "🌧️🏠", phrase: "Refugio", category: "Palabra Aleatoria" },
  { emoji: "🏜️🐪", phrase: "Desierto", category: "Palabra Aleatoria" },
  { emoji: "👁️👁️", phrase: "Mirada", category: "Palabra Aleatoria" },
  { emoji: "🎁😲", phrase: "Sorpresa", category: "Palabra Aleatoria" },
  { emoji: "😈👦", phrase: "Travesura", category: "Palabra Aleatoria" },
  { emoji: "🎩✨", phrase: "Ilusión", category: "Palabra Aleatoria" },
  { emoji: "🪞👤", phrase: "Espejo", category: "Palabra Aleatoria" },
  { emoji: "🙈🌳", phrase: "Escondite", category: "Palabra Aleatoria" },
  { emoji: "⚔️🛡️", phrase: "Desafío", category: "Palabra Aleatoria" },
  { emoji: "👁️⬇️⬆️", phrase: "Parpadeo", category: "Palabra Aleatoria" },
  { emoji: "📸✨", phrase: "Destello", category: "Palabra Aleatoria" }
];
