import { Challenge } from '../types';

export const INITIAL_CHALLENGES: Challenge[] = [
  // CINE & ENTRETENIMIENTO
  { emoji: "🤫🐑", phrase: "El silencio de los corderos", category: "Arte", subcategory: "Cine" },
  { emoji: "🚢🧊", phrase: "Titanic", category: "Arte", subcategory: "Cine" },
  { emoji: "👑🦁", phrase: "El Rey León", category: "Arte", subcategory: "Cine" },
  { emoji: "🌌🎨", phrase: "La noche estrellada", category: "Arte", subcategory: "Pintura" },
  { emoji: "🃏🤡🦇", phrase: "Joker", category: "Arte", subcategory: "Cine" },
  { emoji: "🏠🎈🎈", phrase: "Up", category: "Arte", subcategory: "Cine" },
  { emoji: "🎸💀🇲🇽", phrase: "Coco", category: "Arte", subcategory: "Cine" },
  { emoji: "🎻🎼🧛‍♂️", phrase: "El Fantasma de la Ópera", category: "Arte", subcategory: "Música" },
  { emoji: "⚡👓🧙‍♂️", phrase: "Harry Potter", category: "Arte", subcategory: "Cine" },
  { emoji: "⚔️🌌🛸", phrase: "Star Wars", category: "Arte", subcategory: "Cine" },
  { emoji: "🦷🦈🌊", phrase: "Tiburón", category: "Arte", subcategory: "Cine" },
  { emoji: "🦖🏝️🚗", phrase: "Jurassic Park", category: "Arte", subcategory: "Cine" },
  { emoji: "🕷️🏙️🕸️", phrase: "Spider-Man", category: "Arte", subcategory: "Cine" },
  { emoji: "🥊🏙️🏆", phrase: "Rocky", category: "Arte", subcategory: "Cine" },
  { emoji: "🕴️💊🕶️", phrase: "The Matrix", category: "Arte", subcategory: "Cine" },
  { emoji: "🏹🧝‍♂️💍", phrase: "El Señor de los Anillos", category: "Arte", subcategory: "Cine" },
  { emoji: "🍫🏭🏭", phrase: "Charlie y la fábrica de chocolate", category: "Arte", subcategory: "Cine" },
  { emoji: "🧟‍♂️🏫🏃‍♂️", phrase: "The Walking Dead", category: "Arte", subcategory: "Serie" },
  { emoji: "🏰👸🐉", phrase: "Juego de Tronos", category: "Arte", subcategory: "Serie" },
  { emoji: "🧸🎞️🤠", phrase: "Toy Story", category: "Arte", subcategory: "Cine" },
  { emoji: "👽👉🏠", phrase: "E.T.", category: "Arte", subcategory: "Cine" },
  { emoji: "🏃‍♂️💨🍫", phrase: "Forrest Gump", category: "Arte", subcategory: "Cine" },
  { emoji: "🕶️🧔🔫", phrase: "John Wick", category: "Arte", subcategory: "Cine" },
  { emoji: "🎩🐰🕳️", phrase: "Alicia en el país de las maravillas", category: "Arte", subcategory: "Cine" },

  // MÚSICA
  { emoji: "👑🐝", phrase: "Beyoncé", category: "Arte", subcategory: "Música" },
  { emoji: "🎸🇬🇧💇‍♂️", phrase: "The Beatles", category: "Arte", subcategory: "Música" },
  { emoji: "🕺🧤✨", phrase: "Michael Jackson", category: "Arte", subcategory: "Música" },
  { emoji: "👑🎸🎤", phrase: "Queen", category: "Arte", subcategory: "Música" },
  { emoji: "🔫🌹🎸", phrase: "Guns N' Roses", category: "Arte", subcategory: "Música" },
  { emoji: "🔥💃🎷", phrase: "Rosalía", category: "Arte", subcategory: "Música" },
  { emoji: "👱‍♀️🎤🎹", phrase: "Taylor Swift", category: "Arte", subcategory: "Música" },
  { emoji: "🍍🍕🏖️", phrase: "Bad Bunny", category: "Arte", subcategory: "Música" },

  // GEOGRAFÍA
  { emoji: "🥖🇫🇷🥐", phrase: "Francia", category: "Geografía", subcategory: "Países" },
  { emoji: "🍕🇮🇹🏟️", phrase: "Italia", category: "Geografía", subcategory: "Países" },
  { emoji: "⛩️🇯🇵🍱", phrase: "Japón", category: "Geografía", subcategory: "Países" },
  { emoji: "🌆🍎🗽", phrase: "Nueva York", aliases: ["New York", "NYC"], category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🎡🇬🇧☕", phrase: "Londres", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🧱🐉🇨🇳", phrase: "La Gran Muralla China", category: "Geografía", subcategory: "Monumento" },
  { emoji: "⛰️🏔️🧗", phrase: "Everest", category: "Geografía", subcategory: "Naturaleza" },
  { emoji: "🏜️🐪🇪🇬", phrase: "Egipto", category: "Geografía", subcategory: "Países" },
  { emoji: "🏛️🇬🇷🐚", phrase: "Atenas", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🏟️🇧🇷💃", phrase: "Brasil", category: "Geografía", subcategory: "Países" },
  { emoji: "🐨🇦🇺🏄‍♂️", phrase: "Australia", category: "Geografía", subcategory: "Países" },
  { emoji: "🏰🇩🇪🍺", phrase: "Alemania", category: "Geografía", subcategory: "Países" },
  { emoji: "🚠🇨🇭🧀", phrase: "Suiza", category: "Geografía", subcategory: "Países" },
  { emoji: "🍁🇨🇦🏒", phrase: "Canadá", category: "Geografía", subcategory: "Países" },
  { emoji: "👗🇪🇸🥘", phrase: "España", category: "Geografía", subcategory: "Países" },
  { emoji: "🌊🇵🇹⛪", phrase: "Portugal", category: "Geografía", subcategory: "Países" },
  { emoji: "🌷🇳🇱🚲", phrase: "Países Bajos", aliases: ["Holanda"], category: "Geografía", subcategory: "Países" },
  { emoji: "🏜️🏜️🔥", phrase: "Desierto", category: "Geografía", subcategory: "Naturaleza" },
  { emoji: "🌊🎭🇮🇹", phrase: "Venecia", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🗼🌉🌉", phrase: "San Francisco", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🏗️🏙️🇦🇪", phrase: "Dubai", category: "Geografía", subcategory: "Ciudades" },

  // HISTORIA Y PERSONAJES
  { emoji: "🐴🔥🗼", phrase: "Troya", category: "Historia", subcategory: "Guerra" },
  { emoji: "💣🇯🇵☢️", phrase: "Hiroshima", category: "Historia", subcategory: "Guerra" },
  { emoji: "👑🤴🛡️", phrase: "Reyes Católicos", category: "Historia", subcategory: "Reino" },
  { emoji: "🏺🔱🏛️", phrase: "Grecia Antigua", category: "Historia", subcategory: "Civilización" },
  { emoji: "🚀🌕👨‍🚀", phrase: "Llegada del hombre a la Luna", category: "Historia", subcategory: "Hito" },
  { emoji: "⛴️🗺️🌎", phrase: "Descubrimiento de América", category: "Historia", subcategory: "Hito" },
  { emoji: "🚂💨🏭", phrase: "Revolución Industrial", category: "Historia", subcategory: "Hito" },
  { emoji: "🧱⚒️🇷🇺", phrase: "Muro de Berlín", category: "Historia", subcategory: "Hito" },
  { emoji: "🍐🏰🇫🇷", phrase: "Napoleón", category: "Historia", subcategory: "Personaje" },
  { emoji: "📜🖋️✍️", phrase: "Shakespeare", category: "Historia", subcategory: "Personaje" },
  { emoji: "💡⚡👴", phrase: "Einstein", category: "Historia", subcategory: "Personaje" },
  { emoji: "🍎📐📉", phrase: "Newton", category: "Historia", subcategory: "Personaje" },
  { emoji: "🛸🏛️🇪🇬", phrase: "Cleopatra", category: "Historia", subcategory: "Personaje" },
  { emoji: "🎨🧔🚁", phrase: "Leonardo da Vinci", category: "Historia", subcategory: "Personaje" },

  // REFRANES
  { emoji: "💧🚫🍷", phrase: "Agua que no has de beber déjala correr", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🐦✊🌳", phrase: "Más vale pájaro en mano que ciento volando", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🐴👀🤐", phrase: "A caballo regalado no le mires el diente", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🐶🗣️🦷", phrase: "Perro ladrador poco mordedor", category: "Refranes", subcategory: "Dicho" },
  { emoji: "👄🪰🤐", phrase: "En boca cerrada no entran moscas", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🐢💨🐇", phrase: "Vísteme despacio que tengo prisa", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🍞🍞🍷🍷", phrase: "Al pan, pan y al vino, vino", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🍎🌳📍", phrase: "La manzana no cae lejos del árbol", category: "Refranes", subcategory: "Dicho" },
  { emoji: "🌙🏙️🌄", phrase: "A quien madruga Dios le ayuda", category: "Refranes", subcategory: "Dicho" },
  { emoji: "👞🛠️🚶‍♂️", phrase: "Zapatero a tus zapatos", category: "Refranes", subcategory: "Dicho" },

  // DEPORTE
  { emoji: "⚽🏆🇦🇷", phrase: "Mundial de fútbol", category: "Deporte", subcategory: "Fútbol" },
  { emoji: "🏎️🏁🔥", phrase: "Fórmula 1", category: "Deporte", subcategory: "Motor" },
  { emoji: "🎾🇪🇸🐗", phrase: "Rafa Nadal", category: "Deporte", subcategory: "Tenis" },
  { emoji: "🏀🇺🇸🐐", phrase: "Michael Jordan", category: "Deporte", subcategory: "Baloncesto" },
  { emoji: "🏊‍♂️🥇🇺🇸", phrase: "Michael Phelps", category: "Deporte", subcategory: "Natación" },
  { emoji: "🥊🐝🦋", phrase: "Muhammad Ali", category: "Deporte", subcategory: "Boxeo" },
  { emoji: "🚲🏔️🇫🇷", phrase: "Tour de Francia", category: "Deporte", subcategory: "Ciclismo" },
  { emoji: "🏀🥇🦍", phrase: "LeBron James", category: "Deporte", subcategory: "Baloncesto" },
  { emoji: "⚽🐐🇵🇹", phrase: "Cristiano Ronaldo", category: "Deporte", subcategory: "Fútbol" },
  { emoji: "🎾👑🇨🇭", phrase: "Roger Federer", category: "Deporte", subcategory: "Tenis" },

  // GASTRONOMÍA
  { emoji: "🥘🐰🐌", phrase: "Paella", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🌮🇲🇽🌶️", phrase: "Taco", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍣🇯🇵🍱", phrase: "Sushi", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍕🇮🇹🧀", phrase: "Pizza", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🍔🇺🇸🍟", phrase: "Hamburguesa", category: "Gastronomía", subcategory: "Plato" },
  { emoji: "🥐🇫🇷☕", phrase: "Croissant", category: "Gastronomía", subcategory: "Reposteria" },
  { emoji: "🍲🍛🇮🇳", phrase: "Curry", aliases: ["Arroz al curry", "Tikka Masala"], category: "Gastronomía", subcategory: "Plato" },

  // PALABRA ALEATORIA / FONÉTICA
  { emoji: "✏️🎀🔵", phrase: "Lapislázuli", category: "Palabra Aleatoria" },
  { emoji: "🦶🧗‍♂️", phrase: "Pies de gato", category: "Palabra Aleatoria" },
  { emoji: "🧦🌙", phrase: "Media luna", category: "Palabra Aleatoria" },
  { emoji: "🐅⚖️", phrase: "Trabalenguas", category: "Palabra Aleatoria" },
  { emoji: "🥚👣", phrase: "Pisar huevos", category: "Palabra Aleatoria" },
  { emoji: "👁️🏔️", phrase: "Ojo de buey", category: "Palabra Aleatoria" },
  { emoji: "👂👂🚿", phrase: "Ducha de orejas", category: "Palabra Aleatoria" },
  { emoji: "🧛‍♂️🥩", phrase: "Chuleta de vampiro", category: "Palabra Aleatoria" },
  { emoji: "🌈🦎", phrase: "Camaleón", category: "Palabra Aleatoria" },
  { emoji: "🏹🎯", phrase: "Tiro con arco", category: "Palabra Aleatoria" },
  
  // MÁS PELÍCULAS
  { emoji: "🐜👨", phrase: "Ant-Man", category: "Arte", subcategory: "Cine" },
  { emoji: "🌑🧛‍♂️🏰", phrase: "Drácula", category: "Arte", subcategory: "Cine" },
  { emoji: "🤡🎈🎈", phrase: "It", category: "Arte", subcategory: "Cine" },
  { emoji: "🧸🚲🏚️", phrase: "E.T.", category: "Arte", subcategory: "Cine" },
  { emoji: "🎩✨🚂", phrase: "Harry Potter", category: "Arte", subcategory: "Cine" },
  { emoji: "🏹🔥👧", phrase: "Los Juegos del Hambre", category: "Arte", subcategory: "Cine" },
  { emoji: "🎩🎩🐰", phrase: "El truco final", category: "Arte", subcategory: "Cine" },
  { emoji: "🏙️🦾👮‍♂️", phrase: "RoboCop", category: "Arte", subcategory: "Cine" },
  { emoji: "👹🏰🌹", phrase: "La Bella y la Bestia", category: "Arte", subcategory: "Cine" },

  // MÁS PAÍSES
  { emoji: "🥟🇨🇳🐉", phrase: "China", category: "Geografía", subcategory: "Países" },
  { emoji: "🍝🇮🇹🏟️", phrase: "Italia", category: "Geografía", subcategory: "Países" },
  { emoji: "🍻🇩🇪🥨", phrase: "Alemania", category: "Geografía", subcategory: "Países" },
  { emoji: "🥘🇪🇸☀️", phrase: "España", category: "Geografía", subcategory: "Países" },
  { emoji: "🌵🇲🇽🌮", phrase: "México", category: "Geografía", subcategory: "Países" },
  { emoji: "🏈🇺🇸🗽", phrase: "Estados Unidos", category: "Geografía", subcategory: "Países" },
  { emoji: "🐘🇹🇭🏝️", phrase: "Tailandia", category: "Geografía", subcategory: "Países" },
  { emoji: "🍷🇦🇷🏔️", phrase: "Argentina", category: "Geografía", subcategory: "Países" },
  { emoji: "🍛🇮🇳🛕", phrase: "India", category: "Geografía", subcategory: "Países" },
  { emoji: "🦁🇿🇦🦒", phrase: "Sudáfrica", category: "Geografía", subcategory: "Países" },
  { emoji: "🌋🇮🇸❄️", phrase: "Islandia", category: "Geografía", subcategory: "Países" },
  
  // MÁS CIUDADES
  { emoji: "💂‍♂️🇬🇧🎡", phrase: "Londres", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🥐🇫🇷🗼", phrase: "París", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🍎🏦🚕", phrase: "Nueva York", aliases: ["New York", "NYC"], category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🛶🇮🇹🎭", phrase: "Venecia", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🍺🇩🇪🎡", phrase: "Múnich", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "⛩️🇯🇵🏙️", phrase: "Tokio", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🌉🇺🇸🌁", phrase: "San Francisco", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🏛️🇬🇷🏺", phrase: "Atenas", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🐨🇦🇺🏢", phrase: "Sídney", category: "Geografía", subcategory: "Ciudades" },
  { emoji: "🏰🇷🇺❄️", phrase: "Moscú", category: "Geografía", subcategory: "Ciudades" },

  // MÁS DEPORTES Y PERSONAJES
  { emoji: "⚽🐐🇦🇷", phrase: "Messi", category: "Deporte", subcategory: "Fútbol" },
  { emoji: "🏀🐐🇺🇸", phrase: "Michael Jordan", category: "Deporte", subcategory: "Baloncesto" },
  { emoji: "🎾👑🇪🇸", phrase: "Rafael Nadal", category: "Deporte", subcategory: "Tenis" },
  { emoji: "🏎️🏎️🏆", phrase: "Fórmula 1", category: "Deporte", subcategory: "Motor" },
  { emoji: "🏌️‍♂️⛳🌳", phrase: "Golf", category: "Deporte" },
  { emoji: "🏐🏖️☀️", phrase: "Voley Playa", category: "Deporte" },

  // MÁS REFRANES
  { emoji: "🐒👑🧤", phrase: "Aunque la mona se vista de seda, mona se queda", category: "Refranes" },
  { emoji: "🐕🗣️🚫咬", phrase: "Perro que ladra no muerde", category: "Refranes" },
  { emoji: "🕰️💰", phrase: "El tiempo es oro", category: "Refranes" },
  { emoji: "🌬️🌾🌪️", phrase: "Quien siembra vientos, recoge tempestades", category: "Refranes" },
  { emoji: "🦷🔨🏙️", phrase: "Ojo por ojo, diente por diente", category: "Refranes" },
  { emoji: "🐟👄💀", phrase: "Por la boca muere el pez", category: "Refranes" },
  { emoji: "🧗‍♂️⬇️", phrase: "Todo lo que sube, tiene que bajar", category: "Refranes" },
  { emoji: "🍞🥖🥖", phrase: "A falta de pan, buenas son tortas", category: "Refranes" }
];


